DATASET_CHOICES = [
    {"label": "F-F Research Data Factors", "value": "F-F_Research_Data_Factors"},
    {
        "label": "F-F Research Data Factors weekly",
        "value": "F-F_Research_Data_Factors_weekly",
    },
    {
        "label": "F-F Research Data Factors daily",
        "value": "F-F_Research_Data_Factors_daily",
    },
    {
        "label": "F-F Research Data 5 Factors 2x3",
        "value": "F-F_Research_Data_5_Factors_2x3",
    },
    {
        "label": "F-F Research Data 5 Factors 2x3 daily",
        "value": "F-F_Research_Data_5_Factors_2x3_daily",
    },
    {"label": "Portfolios Formed on ME", "value": "Portfolios_Formed_on_ME"},
    {
        "label": "Portfolios Formed on ME Wout Div",
        "value": "Portfolios_Formed_on_ME_Wout_Div",
    },
    {
        "label": "Portfolios Formed on ME Daily",
        "value": "Portfolios_Formed_on_ME_Daily",
    },
    {"label": "Portfolios Formed on BE-ME", "value": "Portfolios_Formed_on_BE-ME"},
    {
        "label": "Portfolios Formed on BE-ME Wout Div",
        "value": "Portfolios_Formed_on_BE-ME_Wout_Div",
    },
    {
        "label": "Portfolios Formed on BE-ME Daily",
        "value": "Portfolios_Formed_on_BE-ME_Daily",
    },
    {"label": "Portfolios Formed on OP", "value": "Portfolios_Formed_on_OP"},
    {
        "label": "Portfolios Formed on OP Wout Div",
        "value": "Portfolios_Formed_on_OP_Wout_Div",
    },
    {
        "label": "Portfolios Formed on OP Daily",
        "value": "Portfolios_Formed_on_OP_Daily",
    },
    {"label": "Portfolios Formed on INV", "value": "Portfolios_Formed_on_INV"},
    {
        "label": "Portfolios Formed on INV Wout Div",
        "value": "Portfolios_Formed_on_INV_Wout_Div",
    },
    {
        "label": "Portfolios Formed on INV Daily",
        "value": "Portfolios_Formed_on_INV_Daily",
    },
    {"label": "6 Portfolios 2x3", "value": "6_Portfolios_2x3"},
    {"label": "6 Portfolios 2x3 Wout Div", "value": "6_Portfolios_2x3_Wout_Div"},
    {"label": "6 Portfolios 2x3 weekly", "value": "6_Portfolios_2x3_weekly"},
    {"label": "6 Portfolios 2x3 daily", "value": "6_Portfolios_2x3_daily"},
    {"label": "25 Portfolios 5x5", "value": "25_Portfolios_5x5"},
    {"label": "25 Portfolios 5x5 Wout Div", "value": "25_Portfolios_5x5_Wout_Div"},
    {"label": "25 Portfolios 5x5 Daily", "value": "25_Portfolios_5x5_Daily"},
    {"label": "100 Portfolios 10x10", "value": "100_Portfolios_10x10"},
    {
        "label": "100 Portfolios 10x10 Wout Div",
        "value": "100_Portfolios_10x10_Wout_Div",
    },
    {"label": "100 Portfolios 10x10 Daily", "value": "100_Portfolios_10x10_Daily"},
    {"label": "6 Portfolios ME OP 2x3", "value": "6_Portfolios_ME_OP_2x3"},
    {
        "label": "6 Portfolios ME OP 2x3 Wout Div",
        "value": "6_Portfolios_ME_OP_2x3_Wout_Div",
    },
    {"label": "6 Portfolios ME OP 2x3 daily", "value": "6_Portfolios_ME_OP_2x3_daily"},
    {"label": "25 Portfolios ME OP 5x5", "value": "25_Portfolios_ME_OP_5x5"},
    {
        "label": "25 Portfolios ME OP 5x5 Wout Div",
        "value": "25_Portfolios_ME_OP_5x5_Wout_Div",
    },
    {
        "label": "25 Portfolios ME OP 5x5 daily",
        "value": "25_Portfolios_ME_OP_5x5_daily",
    },
    {"label": "100 Portfolios ME OP 10x10", "value": "100_Portfolios_ME_OP_10x10"},
    {
        "label": "100 Portfolios 10x10 ME OP Wout Div",
        "value": "100_Portfolios_10x10_ME_OP_Wout_Div",
    },
    {
        "label": "100 Portfolios ME OP 10x10 daily",
        "value": "100_Portfolios_ME_OP_10x10_daily",
    },
    {"label": "6 Portfolios ME INV 2x3", "value": "6_Portfolios_ME_INV_2x3"},
    {
        "label": "6 Portfolios ME INV 2x3 Wout Div",
        "value": "6_Portfolios_ME_INV_2x3_Wout_Div",
    },
    {
        "label": "6 Portfolios ME INV 2x3 daily",
        "value": "6_Portfolios_ME_INV_2x3_daily",
    },
    {"label": "25 Portfolios ME INV 5x5", "value": "25_Portfolios_ME_INV_5x5"},
    {
        "label": "25 Portfolios ME INV 5x5 Wout Div",
        "value": "25_Portfolios_ME_INV_5x5_Wout_Div",
    },
    {
        "label": "25 Portfolios ME INV 5x5 daily",
        "value": "25_Portfolios_ME_INV_5x5_daily",
    },
    {"label": "100 Portfolios ME INV 10x10", "value": "100_Portfolios_ME_INV_10x10"},
    {
        "label": "100 Portfolios 10x10 ME INV Wout Div",
        "value": "100_Portfolios_10x10_ME_INV_Wout_Div",
    },
    {
        "label": "100 Portfolios ME INV 10x10 daily",
        "value": "100_Portfolios_ME_INV_10x10_daily",
    },
    {"label": "25 Portfolios BEME OP 5x5", "value": "25_Portfolios_BEME_OP_5x5"},
    {
        "label": "25 Portfolios BEME OP 5x5 Wout Div",
        "value": "25_Portfolios_BEME_OP_5x5_Wout_Div",
    },
    {
        "label": "25 Portfolios BEME OP 5x5 daily",
        "value": "25_Portfolios_BEME_OP_5x5_daily",
    },
    {"label": "25 Portfolios BEME INV 5x5", "value": "25_Portfolios_BEME_INV_5x5"},
    {
        "label": "25 Portfolios BEME INV 5x5 Wout Div",
        "value": "25_Portfolios_BEME_INV_5x5_Wout_Div",
    },
    {
        "label": "25 Portfolios BEME INV 5x5 daily",
        "value": "25_Portfolios_BEME_INV_5x5_daily",
    },
    {"label": "25 Portfolios OP INV 5x5", "value": "25_Portfolios_OP_INV_5x5"},
    {
        "label": "25 Portfolios OP INV 5x5 Wout Div",
        "value": "25_Portfolios_OP_INV_5x5_Wout_Div",
    },
    {
        "label": "25 Portfolios OP INV 5x5 daily",
        "value": "25_Portfolios_OP_INV_5x5_daily",
    },
    {
        "label": "32 Portfolios ME BEME OP 2x4x4",
        "value": "32_Portfolios_ME_BEME_OP_2x4x4",
    },
    {
        "label": "32 Portfolios ME BEME OP 2x4x4 Wout Div",
        "value": "32_Portfolios_ME_BEME_OP_2x4x4_Wout_Div",
    },
    {
        "label": "32 Portfolios ME BEME INV 2x4x4",
        "value": "32_Portfolios_ME_BEME_INV_2x4x4",
    },
    {
        "label": "32 Portfolios ME BEME INV 2x4x4 Wout Div",
        "value": "32_Portfolios_ME_BEME_INV_2x4x4_Wout_Div",
    },
    {
        "label": "32 Portfolios ME OP INV 2x4x4",
        "value": "32_Portfolios_ME_OP_INV_2x4x4",
    },
    {
        "label": "32 Portfolios ME OP INV 2x4x4 Wout Div",
        "value": "32_Portfolios_ME_OP_INV_2x4x4_Wout_Div",
    },
    {"label": "Portfolios Formed on E-P", "value": "Portfolios_Formed_on_E-P"},
    {
        "label": "Portfolios Formed on E-P Wout Div",
        "value": "Portfolios_Formed_on_E-P_Wout_Div",
    },
    {"label": "Portfolios Formed on CF-P", "value": "Portfolios_Formed_on_CF-P"},
    {
        "label": "Portfolios Formed on CF-P Wout Div",
        "value": "Portfolios_Formed_on_CF-P_Wout_Div",
    },
    {"label": "Portfolios Formed on D-P", "value": "Portfolios_Formed_on_D-P"},
    {
        "label": "Portfolios Formed on D-P Wout Div",
        "value": "Portfolios_Formed_on_D-P_Wout_Div",
    },
    {"label": "6 Portfolios ME EP 2x3", "value": "6_Portfolios_ME_EP_2x3"},
    {
        "label": "6 Portfolios ME EP 2x3 Wout Div",
        "value": "6_Portfolios_ME_EP_2x3_Wout_Div",
    },
    {"label": "6 Portfolios ME CFP 2x3", "value": "6_Portfolios_ME_CFP_2x3"},
    {
        "label": "6 Portfolios ME CFP 2x3 Wout Div",
        "value": "6_Portfolios_ME_CFP_2x3_Wout_Div",
    },
    {"label": "6 Portfolios ME DP 2x3", "value": "6_Portfolios_ME_DP_2x3"},
    {
        "label": "6 Portfolios ME DP 2x3 Wout Div",
        "value": "6_Portfolios_ME_DP_2x3_Wout_Div",
    },
    {"label": "F-F Momentum Factor", "value": "F-F_Momentum_Factor"},
    {"label": "F-F Momentum Factor daily", "value": "F-F_Momentum_Factor_daily"},
    {"label": "6 Portfolios ME Prior 12 2", "value": "6_Portfolios_ME_Prior_12_2"},
    {
        "label": "6 Portfolios ME Prior 12 2 Daily",
        "value": "6_Portfolios_ME_Prior_12_2_Daily",
    },
    {"label": "25 Portfolios ME Prior 12 2", "value": "25_Portfolios_ME_Prior_12_2"},
    {
        "label": "25 Portfolios ME Prior 12 2 Daily",
        "value": "25_Portfolios_ME_Prior_12_2_Daily",
    },
    {"label": "10 Portfolios Prior 12 2", "value": "10_Portfolios_Prior_12_2"},
    {
        "label": "10 Portfolios Prior 12 2 Daily",
        "value": "10_Portfolios_Prior_12_2_Daily",
    },
    {"label": "F-F ST Reversal Factor", "value": "F-F_ST_Reversal_Factor"},
    {"label": "F-F ST Reversal Factor daily", "value": "F-F_ST_Reversal_Factor_daily"},
    {"label": "6 Portfolios ME Prior 1 0", "value": "6_Portfolios_ME_Prior_1_0"},
    {
        "label": "6 Portfolios ME Prior 1 0 Daily",
        "value": "6_Portfolios_ME_Prior_1_0_Daily",
    },
    {"label": "25 Portfolios ME Prior 1 0", "value": "25_Portfolios_ME_Prior_1_0"},
    {
        "label": "25 Portfolios ME Prior 1 0 Daily",
        "value": "25_Portfolios_ME_Prior_1_0_Daily",
    },
    {"label": "10 Portfolios Prior 1 0", "value": "10_Portfolios_Prior_1_0"},
    {
        "label": "10 Portfolios Prior 1 0 Daily",
        "value": "10_Portfolios_Prior_1_0_Daily",
    },
    {"label": "F-F LT Reversal Factor", "value": "F-F_LT_Reversal_Factor"},
    {"label": "F-F LT Reversal Factor daily", "value": "F-F_LT_Reversal_Factor_daily"},
    {"label": "6 Portfolios ME Prior 60 13", "value": "6_Portfolios_ME_Prior_60_13"},
    {
        "label": "6 Portfolios ME Prior 60 13 Daily",
        "value": "6_Portfolios_ME_Prior_60_13_Daily",
    },
    {"label": "25 Portfolios ME Prior 60 13", "value": "25_Portfolios_ME_Prior_60_13"},
    {
        "label": "25 Portfolios ME Prior 60 13 Daily",
        "value": "25_Portfolios_ME_Prior_60_13_Daily",
    },
    {"label": "10 Portfolios Prior 60 13", "value": "10_Portfolios_Prior_60_13"},
    {
        "label": "10 Portfolios Prior 60 13 Daily",
        "value": "10_Portfolios_Prior_60_13_Daily",
    },
    {"label": "Portfolios Formed on AC", "value": "Portfolios_Formed_on_AC"},
    {"label": "25 Portfolios ME AC 5x5", "value": "25_Portfolios_ME_AC_5x5"},
    {"label": "Portfolios Formed on BETA", "value": "Portfolios_Formed_on_BETA"},
    {"label": "25 Portfolios ME BETA 5x5", "value": "25_Portfolios_ME_BETA_5x5"},
    {"label": "Portfolios Formed on NI", "value": "Portfolios_Formed_on_NI"},
    {"label": "25 Portfolios ME NI 5x5", "value": "25_Portfolios_ME_NI_5x5"},
    {"label": "Portfolios Formed on VAR", "value": "Portfolios_Formed_on_VAR"},
    {"label": "25 Portfolios ME VAR 5x5", "value": "25_Portfolios_ME_VAR_5x5"},
    {"label": "Portfolios Formed on RESVAR", "value": "Portfolios_Formed_on_RESVAR"},
    {"label": "25 Portfolios ME RESVAR 5x5", "value": "25_Portfolios_ME_RESVAR_5x5"},
    {"label": "5 Industry Portfolios", "value": "5_Industry_Portfolios"},
    {
        "label": "5 Industry Portfolios Wout Div",
        "value": "5_Industry_Portfolios_Wout_Div",
    },
    {"label": "5 Industry Portfolios daily", "value": "5_Industry_Portfolios_daily"},
    {"label": "10 Industry Portfolios", "value": "10_Industry_Portfolios"},
    {
        "label": "10 Industry Portfolios Wout Div",
        "value": "10_Industry_Portfolios_Wout_Div",
    },
    {"label": "10 Industry Portfolios daily", "value": "10_Industry_Portfolios_daily"},
    {"label": "12 Industry Portfolios", "value": "12_Industry_Portfolios"},
    {
        "label": "12 Industry Portfolios Wout Div",
        "value": "12_Industry_Portfolios_Wout_Div",
    },
    {"label": "12 Industry Portfolios daily", "value": "12_Industry_Portfolios_daily"},
    {"label": "17 Industry Portfolios", "value": "17_Industry_Portfolios"},
    {
        "label": "17 Industry Portfolios Wout Div",
        "value": "17_Industry_Portfolios_Wout_Div",
    },
    {"label": "17 Industry Portfolios daily", "value": "17_Industry_Portfolios_daily"},
    {"label": "30 Industry Portfolios", "value": "30_Industry_Portfolios"},
    {
        "label": "30 Industry Portfolios Wout Div",
        "value": "30_Industry_Portfolios_Wout_Div",
    },
    {"label": "30 Industry Portfolios daily", "value": "30_Industry_Portfolios_daily"},
    {"label": "38 Industry Portfolios", "value": "38_Industry_Portfolios"},
    {
        "label": "38 Industry Portfolios Wout Div",
        "value": "38_Industry_Portfolios_Wout_Div",
    },
    {"label": "38 Industry Portfolios daily", "value": "38_Industry_Portfolios_daily"},
    {"label": "48 Industry Portfolios", "value": "48_Industry_Portfolios"},
    {
        "label": "48 Industry Portfolios Wout Div",
        "value": "48_Industry_Portfolios_Wout_Div",
    },
    {"label": "48 Industry Portfolios daily", "value": "48_Industry_Portfolios_daily"},
    {"label": "49 Industry Portfolios", "value": "49_Industry_Portfolios"},
    {
        "label": "49 Industry Portfolios Wout Div",
        "value": "49_Industry_Portfolios_Wout_Div",
    },
    {"label": "49 Industry Portfolios daily", "value": "49_Industry_Portfolios_daily"},
    {"label": "ME Breakpoints", "value": "ME_Breakpoints"},
    {"label": "BE-ME Breakpoints", "value": "BE-ME_Breakpoints"},
    {"label": "OP Breakpoints", "value": "OP_Breakpoints"},
    {"label": "INV Breakpoints", "value": "INV_Breakpoints"},
    {"label": "E-P Breakpoints", "value": "E-P_Breakpoints"},
    {"label": "CF-P Breakpoints", "value": "CF-P_Breakpoints"},
    {"label": "D-P Breakpoints", "value": "D-P_Breakpoints"},
    {"label": "Prior 2-12 Breakpoints", "value": "Prior_2-12_Breakpoints"},
    {"label": "Developed 3 Factors", "value": "Developed_3_Factors"},
    {"label": "Developed 3 Factors Daily", "value": "Developed_3_Factors_Daily"},
    {"label": "Developed ex US 3 Factors", "value": "Developed_ex_US_3_Factors"},
    {
        "label": "Developed ex US 3 Factors Daily",
        "value": "Developed_ex_US_3_Factors_Daily",
    },
    {"label": "Europe 3 Factors", "value": "Europe_3_Factors"},
    {"label": "Europe 3 Factors Daily", "value": "Europe_3_Factors_Daily"},
    {"label": "Japan 3 Factors", "value": "Japan_3_Factors"},
    {"label": "Japan 3 Factors Daily", "value": "Japan_3_Factors_Daily"},
    {
        "label": "Asia Pacific ex Japan 3 Factors",
        "value": "Asia_Pacific_ex_Japan_3_Factors",
    },
    {
        "label": "Asia Pacific ex Japan 3 Factors Daily",
        "value": "Asia_Pacific_ex_Japan_3_Factors_Daily",
    },
    {"label": "North America 3 Factors", "value": "North_America_3_Factors"},
    {
        "label": "North America 3 Factors Daily",
        "value": "North_America_3_Factors_Daily",
    },
    {"label": "Developed 5 Factors", "value": "Developed_5_Factors"},
    {"label": "Developed 5 Factors Daily", "value": "Developed_5_Factors_Daily"},
    {"label": "Developed ex US 5 Factors", "value": "Developed_ex_US_5_Factors"},
    {
        "label": "Developed ex US 5 Factors Daily",
        "value": "Developed_ex_US_5_Factors_Daily",
    },
    {"label": "Europe 5 Factors", "value": "Europe_5_Factors"},
    {"label": "Europe 5 Factors Daily", "value": "Europe_5_Factors_Daily"},
    {"label": "Japan 5 Factors", "value": "Japan_5_Factors"},
    {"label": "Japan 5 Factors Daily", "value": "Japan_5_Factors_Daily"},
    {
        "label": "Asia Pacific ex Japan 5 Factors",
        "value": "Asia_Pacific_ex_Japan_5_Factors",
    },
    {
        "label": "Asia Pacific ex Japan 5 Factors Daily",
        "value": "Asia_Pacific_ex_Japan_5_Factors_Daily",
    },
    {"label": "North America 5 Factors", "value": "North_America_5_Factors"},
    {
        "label": "North America 5 Factors Daily",
        "value": "North_America_5_Factors_Daily",
    },
    {"label": "Developed Mom Factor", "value": "Developed_Mom_Factor"},
    {"label": "Developed Mom Factor Daily", "value": "Developed_Mom_Factor_Daily"},
    {"label": "Developed ex US Mom Factor", "value": "Developed_ex_US_Mom_Factor"},
    {
        "label": "Developed ex US Mom Factor Daily",
        "value": "Developed_ex_US_Mom_Factor_Daily",
    },
    {"label": "Europe Mom Factor", "value": "Europe_Mom_Factor"},
    {"label": "Europe Mom Factor Daily", "value": "Europe_Mom_Factor_Daily"},
    {"label": "Japan Mom Factor", "value": "Japan_Mom_Factor"},
    {"label": "Japan Mom Factor Daily", "value": "Japan_Mom_Factor_Daily"},
    {
        "label": "Asia Pacific ex Japan MOM Factor",
        "value": "Asia_Pacific_ex_Japan_MOM_Factor",
    },
    {
        "label": "Asia Pacific ex Japan MOM Factor Daily",
        "value": "Asia_Pacific_ex_Japan_MOM_Factor_Daily",
    },
    {"label": "North America Mom Factor", "value": "North_America_Mom_Factor"},
    {
        "label": "North America Mom Factor Daily",
        "value": "North_America_Mom_Factor_Daily",
    },
    {
        "label": "Developed 6 Portfolios ME BE-ME",
        "value": "Developed_6_Portfolios_ME_BE-ME",
    },
    {
        "label": "Developed 6 Portfolios ME BE-ME daily",
        "value": "Developed_6_Portfolios_ME_BE-ME_daily",
    },
    {
        "label": "Developed ex US 6 Portfolios ME BE-ME",
        "value": "Developed_ex_US_6_Portfolios_ME_BE-ME",
    },
    {
        "label": "Developed ex US 6 Portfolios ME BE-ME daily",
        "value": "Developed_ex_US_6_Portfolios_ME_BE-ME_daily",
    },
    {"label": "Europe 6 Portfolios ME BE-ME", "value": "Europe_6_Portfolios_ME_BE-ME"},
    {
        "label": "Europe 6 Portfolios ME BE-ME daily",
        "value": "Europe_6_Portfolios_ME_BE-ME_daily",
    },
    {"label": "Japan 6 Portfolios ME BE-ME", "value": "Japan_6_Portfolios_ME_BE-ME"},
    {
        "label": "Japan 6 Portfolios ME BE-ME daily",
        "value": "Japan_6_Portfolios_ME_BE-ME_daily",
    },
    {
        "label": "Asia Pacific ex Japan 6 Portfolios ME BE-ME",
        "value": "Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME",
    },
    {
        "label": "Asia Pacific ex Japan 6 Portfolios ME BE-ME daily",
        "value": "Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME_daily",
    },
    {
        "label": "North America 6 Portfolios ME BE-ME",
        "value": "North_America_6_Portfolios_ME_BE-ME",
    },
    {
        "label": "North America 6 Portfolios ME BE-ME daily",
        "value": "North_America_6_Portfolios_ME_BE-ME_daily",
    },
    {
        "label": "Developed 25 Portfolios ME BE-ME",
        "value": "Developed_25_Portfolios_ME_BE-ME",
    },
    {
        "label": "Developed 25 Portfolios ME BE-ME daily",
        "value": "Developed_25_Portfolios_ME_BE-ME_daily",
    },
    {
        "label": "Developed ex US 25 Portfolios ME BE-ME",
        "value": "Developed_ex_US_25_Portfolios_ME_BE-ME",
    },
    {
        "label": "Developed ex US 25 Portfolios ME BE-ME daily",
        "value": "Developed_ex_US_25_Portfolios_ME_BE-ME_daily",
    },
    {
        "label": "Europe 25 Portfolios ME BE-ME",
        "value": "Europe_25_Portfolios_ME_BE-ME",
    },
    {
        "label": "Europe 25 Portfolios ME BE-ME daily",
        "value": "Europe_25_Portfolios_ME_BE-ME_daily",
    },
    {"label": "Japan 25 Portfolios ME BE-ME", "value": "Japan_25_Portfolios_ME_BE-ME"},
    {
        "label": "Japan 25 Portfolios ME BE-ME daily",
        "value": "Japan_25_Portfolios_ME_BE-ME_daily",
    },
    {
        "label": "Asia Pacific ex Japan 25 Portfolios ME BE-ME",
        "value": "Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME",
    },
    {
        "label": "Asia Pacific ex Japan 25 Portfolios ME BE-ME daily",
        "value": "Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME_daily",
    },
    {
        "label": "North America 25 Portfolios ME BE-ME",
        "value": "North_America_25_Portfolios_ME_BE-ME",
    },
    {
        "label": "North America 25 Portfolios ME BE-ME daily",
        "value": "North_America_25_Portfolios_ME_BE-ME_daily",
    },
    {"label": "Developed 6 Portfolios ME OP", "value": "Developed_6_Portfolios_ME_OP"},
    {
        "label": "Developed 6 Portfolios ME OP Daily",
        "value": "Developed_6_Portfolios_ME_OP_Daily",
    },
    {
        "label": "Developed ex US 6 Portfolios ME OP",
        "value": "Developed_ex_US_6_Portfolios_ME_OP",
    },
    {
        "label": "Developed ex US 6 Portfolios ME OP Daily",
        "value": "Developed_ex_US_6_Portfolios_ME_OP_Daily",
    },
    {"label": "Europe 6 Portfolios ME OP", "value": "Europe_6_Portfolios_ME_OP"},
    {
        "label": "Europe 6 Portfolios ME OP Daily",
        "value": "Europe_6_Portfolios_ME_OP_Daily",
    },
    {"label": "Japan 6 Portfolios ME OP", "value": "Japan_6_Portfolios_ME_OP"},
    {
        "label": "Japan 6 Portfolios ME OP Daily",
        "value": "Japan_6_Portfolios_ME_OP_Daily",
    },
    {
        "label": "Asia Pacific ex Japan 6 Portfolios ME OP",
        "value": "Asia_Pacific_ex_Japan_6_Portfolios_ME_OP",
    },
    {
        "label": "Asia Pacific ex Japan 6 Portfolios ME OP Daily",
        "value": "Asia_Pacific_ex_Japan_6_Portfolios_ME_OP_Daily",
    },
    {
        "label": "North America 6 Portfolios ME OP",
        "value": "North_America_6_Portfolios_ME_OP",
    },
    {
        "label": "North America 6 Portfolios ME OP Daily",
        "value": "North_America_6_Portfolios_ME_OP_Daily",
    },
    {
        "label": "Developed 25 Portfolios ME OP",
        "value": "Developed_25_Portfolios_ME_OP",
    },
    {
        "label": "Developed 25 Portfolios ME OP Daily",
        "value": "Developed_25_Portfolios_ME_OP_Daily",
    },
    {
        "label": "Developed ex US 25 Portfolios ME OP",
        "value": "Developed_ex_US_25_Portfolios_ME_OP",
    },
    {
        "label": "Developed ex US 25 Portfolios ME OP Daily",
        "value": "Developed_ex_US_25_Portfolios_ME_OP_Daily",
    },
    {"label": "Europe 25 Portfolios ME OP", "value": "Europe_25_Portfolios_ME_OP"},
    {
        "label": "Europe 25 Portfolios ME OP Daily",
        "value": "Europe_25_Portfolios_ME_OP_Daily",
    },
    {"label": "Japan 25 Portfolios ME OP", "value": "Japan_25_Portfolios_ME_OP"},
    {
        "label": "Japan 25 Portfolios ME OP Daily",
        "value": "Japan_25_Portfolios_ME_OP_Daily",
    },
    {
        "label": "Asia Pacific ex Japan 25 Portfolios ME OP",
        "value": "Asia_Pacific_ex_Japan_25_Portfolios_ME_OP",
    },
    {
        "label": "Asia Pacific ex Japan 25 Portfolios ME OP Daily",
        "value": "Asia_Pacific_ex_Japan_25_Portfolios_ME_OP_Daily",
    },
    {
        "label": "North America 25 Portfolios ME OP",
        "value": "North_America_25_Portfolios_ME_OP",
    },
    {
        "label": "North America 25 Portfolios ME OP Daily",
        "value": "North_America_25_Portfolios_ME_OP_Daily",
    },
    {
        "label": "Developed 6 Portfolios ME INV",
        "value": "Developed_6_Portfolios_ME_INV",
    },
    {
        "label": "Developed 6 Portfolios ME INV Daily",
        "value": "Developed_6_Portfolios_ME_INV_Daily",
    },
    {
        "label": "Developed ex US 6 Portfolios ME INV",
        "value": "Developed_ex_US_6_Portfolios_ME_INV",
    },
    {
        "label": "Developed ex US 6 Portfolios ME INV Daily",
        "value": "Developed_ex_US_6_Portfolios_ME_INV_Daily",
    },
    {"label": "Europe 6 Portfolios ME INV", "value": "Europe_6_Portfolios_ME_INV"},
    {
        "label": "Europe 6 Portfolios ME INV Daily",
        "value": "Europe_6_Portfolios_ME_INV_Daily",
    },
    {"label": "Japan 6 Portfolios ME INV", "value": "Japan_6_Portfolios_ME_INV"},
    {
        "label": "Japan 6 Portfolios ME INV Daily",
        "value": "Japan_6_Portfolios_ME_INV_Daily",
    },
    {
        "label": "Asia Pacific ex Japan 6 Portfolios ME INV",
        "value": "Asia_Pacific_ex_Japan_6_Portfolios_ME_INV",
    },
    {
        "label": "Asia Pacific ex Japan 6 Portfolios ME INV Daily",
        "value": "Asia_Pacific_ex_Japan_6_Portfolios_ME_INV_Daily",
    },
    {
        "label": "North America 6 Portfolios ME INV",
        "value": "North_America_6_Portfolios_ME_INV",
    },
    {
        "label": "North America 6 Portfolios ME INV Daily",
        "value": "North_America_6_Portfolios_ME_INV_Daily",
    },
    {
        "label": "Developed 25 Portfolios ME INV",
        "value": "Developed_25_Portfolios_ME_INV",
    },
    {
        "label": "Developed 25 Portfolios ME INV Daily",
        "value": "Developed_25_Portfolios_ME_INV_Daily",
    },
    {
        "label": "Developed ex US 25 Portfolios ME INV",
        "value": "Developed_ex_US_25_Portfolios_ME_INV",
    },
    {
        "label": "Developed ex US 25 Portfolios ME INV Daily",
        "value": "Developed_ex_US_25_Portfolios_ME_INV_Daily",
    },
    {"label": "Europe 25 Portfolios ME INV", "value": "Europe_25_Portfolios_ME_INV"},
    {
        "label": "Europe 25 Portfolios ME INV Daily",
        "value": "Europe_25_Portfolios_ME_INV_Daily",
    },
    {"label": "Japan 25 Portfolios ME INV", "value": "Japan_25_Portfolios_ME_INV"},
    {
        "label": "Japan 25 Portfolios ME INV Daily",
        "value": "Japan_25_Portfolios_ME_INV_Daily",
    },
    {
        "label": "Asia Pacific ex Japan 25 Portfolios ME INV",
        "value": "Asia_Pacific_ex_Japan_25_Portfolios_ME_INV",
    },
    {
        "label": "Asia Pacific ex Japan 25 Portfolios ME INV Daily",
        "value": "Asia_Pacific_ex_Japan_25_Portfolios_ME_INV_Daily",
    },
    {
        "label": "North America 25 Portfolios ME INV",
        "value": "North_America_25_Portfolios_ME_INV",
    },
    {
        "label": "North America 25 Portfolios ME INV Daily",
        "value": "North_America_25_Portfolios_ME_INV_Daily",
    },
    {
        "label": "Developed 6 Portfolios ME Prior 12 2",
        "value": "Developed_6_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Developed 6 Portfolios ME Prior 250 20 daily",
        "value": "Developed_6_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "Developed ex US 6 Portfolios ME Prior 12 2",
        "value": "Developed_ex_US_6_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Developed ex US 6 Portfolios ME Prior 250 20 daily",
        "value": "Developed_ex_US_6_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "Europe 6 Portfolios ME Prior 12 2",
        "value": "Europe_6_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Europe 6 Portfolios ME Prior 250 20 daily",
        "value": "Europe_6_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "Japan 6 Portfolios ME Prior 12 2",
        "value": "Japan_6_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Japan 6 Portfolios ME Prior 250 20 daily",
        "value": "Japan_6_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "Asia Pacific ex Japan 6 Portfolios ME Prior 12 2",
        "value": "Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Asia Pacific ex Japan 6 Portfolios ME Prior 250 20 daily",
        "value": "Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "North America 6 Portfolios ME Prior 12 2",
        "value": "North_America_6_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "North America 6 Portfolios ME Prior 250 20 daily",
        "value": "North_America_6_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "Developed 25 Portfolios ME Prior 12 2",
        "value": "Developed_25_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Developed 25 Portfolios ME Prior 250 20 daily",
        "value": "Developed_25_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "Developed ex US 25 Portfolios ME Prior 12 2",
        "value": "Developed_ex_US_25_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Developed ex US 25 Portfolios ME Prior 250 20 daily",
        "value": "Developed_ex_US_25_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "Europe 25 Portfolios ME Prior 12 2",
        "value": "Europe_25_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Europe 25 Portfolios ME Prior 250 20 daily",
        "value": "Europe_25_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "Japan 25 Portfolios ME Prior 12 2",
        "value": "Japan_25_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Japan 25 Portfolios ME Prior 250 20 daily",
        "value": "Japan_25_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "Asia Pacific ex Japan 25 Portfolios ME Prior 12 2",
        "value": "Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Asia Pacific ex Japan 25 Portfolios ME Prior 250 20 daily",
        "value": "Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "North America 25 Portfolios ME Prior 12 2",
        "value": "North_America_25_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "North America 25 Portfolios ME Prior 250 20 daily",
        "value": "North_America_25_Portfolios_ME_Prior_250_20_daily",
    },
    {
        "label": "Developed 32 Portfolios ME BE-ME OP 2x4x4",
        "value": "Developed_32_Portfolios_ME_BE-ME_OP_2x4x4",
    },
    {
        "label": "Developed ex US 32 Portfolios ME BE-ME OP 2x4x4",
        "value": "Developed_ex_US_32_Portfolios_ME_BE-ME_OP_2x4x4",
    },
    {
        "label": "Europe 32 Portfolios ME BE-ME OP 2x4x4",
        "value": "Europe_32_Portfolios_ME_BE-ME_OP_2x4x4",
    },
    {
        "label": "Japan 32 Portfolios ME BE-ME OP 2x4x4",
        "value": "Japan_32_Portfolios_ME_BE-ME_OP_2x4x4",
    },
    {
        "label": "Asia Pacific ex Japan 32 Portfolios ME BE-ME OP 2x4x4",
        "value": "Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_OP_2x4x4",
    },
    {
        "label": "North America 32 Portfolios ME BE-ME OP 2x4x4",
        "value": "North_America_32_Portfolios_ME_BE-ME_OP_2x4x4",
    },
    {
        "label": "Developed 32 Portfolios ME BE-ME INV(TA) 2x4x4",
        "value": "Developed_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4",
    },
    {
        "label": "Developed ex US 32 Portfolios ME BE-ME INV(TA) 2x4x4",
        "value": "Developed_ex_US_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4",
    },
    {
        "label": "Europe 32 Portfolios ME BE-ME INV(TA) 2x4x4",
        "value": "Europe_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4",
    },
    {
        "label": "Japan 32 Portfolios ME BE-ME INV(TA) 2x4x4",
        "value": "Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4",
    },
    {
        "label": "Asia Pacific ex Japan 32 Portfolios ME BE-ME INV(TA) 2x4x4",
        "value": "Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4",
    },
    {
        "label": "North America 32 Portfolios ME BE-ME INV(TA) 2x4x4",
        "value": "North_America_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4",
    },
    {
        "label": "Developed 32 Portfolios ME INV(TA) OP 2x4x4",
        "value": "Developed_32_Portfolios_ME_INV(TA)_OP_2x4x4",
    },
    {
        "label": "Developed ex US 32 Portfolios ME INV(TA) OP 2x4x4",
        "value": "Developed_ex_US_32_Portfolios_ME_INV(TA)_OP_2x4x4",
    },
    {
        "label": "Europe 32 Portfolios ME INV(TA) OP 2x4x4",
        "value": "Europe_32_Portfolios_ME_INV(TA)_OP_2x4x4",
    },
    {
        "label": "Japan 32 Portfolios ME INV(TA) OP 2x4x4",
        "value": "Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4",
    },
    {
        "label": "Asia Pacific ex Japan 32 Portfolios ME INV(TA) OP 2x4x4",
        "value": "Asia_Pacific_ex_Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4",
    },
    {
        "label": "North America 32 Portfolios ME INV(TA) OP 2x4x4",
        "value": "North_America_32_Portfolios_ME_INV(TA)_OP_2x4x4",
    },
    {"label": "Emerging 5 Factors", "value": "Emerging_5_Factors"},
    {"label": "Emerging MOM Factor", "value": "Emerging_MOM_Factor"},
    {
        "label": "Emerging Markets 6 Portfolios ME BE-ME",
        "value": "Emerging_Markets_6_Portfolios_ME_BE-ME",
    },
    {
        "label": "Emerging Markets 6 Portfolios ME OP",
        "value": "Emerging_Markets_6_Portfolios_ME_OP",
    },
    {
        "label": "Emerging Markets 6 Portfolios ME INV",
        "value": "Emerging_Markets_6_Portfolios_ME_INV",
    },
    {
        "label": "Emerging Markets 6 Portfolios ME Prior 12 2",
        "value": "Emerging_Markets_6_Portfolios_ME_Prior_12_2",
    },
    {
        "label": "Emerging Markets 4 Portfolios BE-ME OP",
        "value": "Emerging_Markets_4_Portfolios_BE-ME_OP",
    },
    {
        "label": "Emerging Markets 4 Portfolios OP INV",
        "value": "Emerging_Markets_4_Portfolios_OP_INV",
    },
    {
        "label": "Emerging Markets 4 Portfolios BE-ME INV",
        "value": "Emerging_Markets_4_Portfolios_BE-ME_INV",
    },
]


URL_MAP = {
    "F-F_Research_Data_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_Factors_CSV.zip",
    "F-F_Research_Data_Factors_weekly": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_Factors_weekly_CSV.zip",
    "F-F_Research_Data_Factors_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_Factors_daily_CSV.zip",
    "F-F_Research_Data_5_Factors_2x3": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_5_Factors_2x3_CSV.zip",
    "F-F_Research_Data_5_Factors_2x3_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_5_Factors_2x3_daily_CSV.zip",
    "Portfolios_Formed_on_ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_ME_CSV.zip",
    "Portfolios_Formed_on_ME_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_ME_Wout_Div_CSV.zip",
    "Portfolios_Formed_on_ME_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_ME_Daily_CSV.zip",
    "Portfolios_Formed_on_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_BE-ME_CSV.zip",
    "Portfolios_Formed_on_BE-ME_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_BE-ME_Wout_Div_CSV.zip",
    "Portfolios_Formed_on_BE-ME_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_BE-ME_Daily_CSV.zip",
    "Portfolios_Formed_on_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_OP_CSV.zip",
    "Portfolios_Formed_on_OP_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_OP_Wout_Div_CSV.zip",
    "Portfolios_Formed_on_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_OP_Daily_CSV.zip",
    "Portfolios_Formed_on_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_INV_CSV.zip",
    "Portfolios_Formed_on_INV_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_INV_Wout_Div_CSV.zip",
    "Portfolios_Formed_on_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_INV_Daily_CSV.zip",
    "6_Portfolios_2x3": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_2x3_CSV.zip",
    "6_Portfolios_2x3_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_2x3_Wout_Div_CSV.zip",
    "6_Portfolios_2x3_weekly": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_2x3_weekly_CSV.zip",
    "6_Portfolios_2x3_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_2x3_daily_CSV.zip",
    "25_Portfolios_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_5x5_CSV.zip",
    "25_Portfolios_5x5_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_5x5_Wout_Div_CSV.zip",
    "25_Portfolios_5x5_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_5x5_Daily_CSV.zip",
    "100_Portfolios_10x10": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/100_Portfolios_10x10_CSV.zip",
    "100_Portfolios_10x10_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/100_Portfolios_10x10_Wout_Div_CSV.zip",
    "100_Portfolios_10x10_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/100_Portfolios_10x10_Daily_CSV.zip",
    "6_Portfolios_ME_OP_2x3": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_OP_2x3_CSV.zip",
    "6_Portfolios_ME_OP_2x3_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_OP_2x3_Wout_Div_CSV.zip",
    "6_Portfolios_ME_OP_2x3_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_OP_2x3_daily_CSV.zip",
    "25_Portfolios_ME_OP_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_OP_5x5_CSV.zip",
    "25_Portfolios_ME_OP_5x5_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_OP_5x5_Wout_Div_CSV.zip",
    "25_Portfolios_ME_OP_5x5_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_OP_5x5_daily_CSV.zip",
    "100_Portfolios_ME_OP_10x10": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/100_Portfolios_ME_OP_10x10_CSV.zip",
    "100_Portfolios_10x10_ME_OP_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/100_Portfolios_10x10_ME_OP_Wout_Div_CSV.zip",
    "100_Portfolios_ME_OP_10x10_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/100_Portfolios_ME_OP_10x10_daily_CSV.zip",
    "6_Portfolios_ME_INV_2x3": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_INV_2x3_CSV.zip",
    "6_Portfolios_ME_INV_2x3_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_INV_2x3_Wout_Div_CSV.zip",
    "6_Portfolios_ME_INV_2x3_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_INV_2x3_daily_CSV.zip",
    "25_Portfolios_ME_INV_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_INV_5x5_CSV.zip",
    "25_Portfolios_ME_INV_5x5_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_INV_5x5_Wout_Div_CSV.zip",
    "25_Portfolios_ME_INV_5x5_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_INV_5x5_daily_CSV.zip",
    "100_Portfolios_ME_INV_10x10": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/100_Portfolios_ME_INV_10x10_CSV.zip",
    "100_Portfolios_10x10_ME_INV_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/100_Portfolios_10x10_ME_INV_Wout_Div_CSV.zip",
    "100_Portfolios_ME_INV_10x10_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/100_Portfolios_ME_INV_10x10_daily_CSV.zip",
    "25_Portfolios_BEME_OP_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_BEME_OP_5x5_CSV.zip",
    "25_Portfolios_BEME_OP_5x5_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_BEME_OP_5x5_Wout_Div_CSV.zip",
    "25_Portfolios_BEME_OP_5x5_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_BEME_OP_5x5_daily_CSV.zip",
    "25_Portfolios_BEME_INV_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_BEME_INV_5x5_CSV.zip",
    "25_Portfolios_BEME_INV_5x5_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_BEME_INV_5x5_Wout_Div_CSV.zip",
    "25_Portfolios_BEME_INV_5x5_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_BEME_INV_5x5_daily_CSV.zip",
    "25_Portfolios_OP_INV_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_OP_INV_5x5_CSV.zip",
    "25_Portfolios_OP_INV_5x5_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_OP_INV_5x5_Wout_Div_CSV.zip",
    "25_Portfolios_OP_INV_5x5_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_OP_INV_5x5_daily_CSV.zip",
    "32_Portfolios_ME_BEME_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/32_Portfolios_ME_BEME_OP_2x4x4_CSV.zip",
    "32_Portfolios_ME_BEME_OP_2x4x4_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/32_Portfolios_ME_BEME_OP_2x4x4_Wout_Div_CSV.zip",
    "32_Portfolios_ME_BEME_INV_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/32_Portfolios_ME_BEME_INV_2x4x4_CSV.zip",
    "32_Portfolios_ME_BEME_INV_2x4x4_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/32_Portfolios_ME_BEME_INV_2x4x4_Wout_Div_CSV.zip",
    "32_Portfolios_ME_OP_INV_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/32_Portfolios_ME_OP_INV_2x4x4_CSV.zip",
    "32_Portfolios_ME_OP_INV_2x4x4_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/32_Portfolios_ME_OP_INV_2x4x4_Wout_Div_CSV.zip",
    "Portfolios_Formed_on_E-P": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_E-P_CSV.zip",
    "Portfolios_Formed_on_E-P_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_E-P_Wout_Div_CSV.zip",
    "Portfolios_Formed_on_CF-P": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_CF-P_CSV.zip",
    "Portfolios_Formed_on_CF-P_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_CF-P_Wout_Div_CSV.zip",
    "Portfolios_Formed_on_D-P": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_D-P_CSV.zip",
    "Portfolios_Formed_on_D-P_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_D-P_Wout_Div_CSV.zip",
    "6_Portfolios_ME_EP_2x3": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_EP_2x3_CSV.zip",
    "6_Portfolios_ME_EP_2x3_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_EP_2x3_Wout_Div_CSV.zip",
    "6_Portfolios_ME_CFP_2x3": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_CFP_2x3_CSV.zip",
    "6_Portfolios_ME_CFP_2x3_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_CFP_2x3_Wout_Div_CSV.zip",
    "6_Portfolios_ME_DP_2x3": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_DP_2x3_CSV.zip",
    "6_Portfolios_ME_DP_2x3_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_DP_2x3_Wout_Div_CSV.zip",
    "F-F_Momentum_Factor": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Momentum_Factor_CSV.zip",
    "F-F_Momentum_Factor_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Momentum_Factor_daily_CSV.zip",
    "6_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_Prior_12_2_CSV.zip",
    "6_Portfolios_ME_Prior_12_2_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_Prior_12_2_Daily_CSV.zip",
    "25_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_Prior_12_2_CSV.zip",
    "25_Portfolios_ME_Prior_12_2_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_Prior_12_2_Daily_CSV.zip",
    "10_Portfolios_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/10_Portfolios_Prior_12_2_CSV.zip",
    "10_Portfolios_Prior_12_2_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/10_Portfolios_Prior_12_2_Daily_CSV.zip",
    "F-F_ST_Reversal_Factor": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_ST_Reversal_Factor_CSV.zip",
    "F-F_ST_Reversal_Factor_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_ST_Reversal_Factor_daily_CSV.zip",
    "6_Portfolios_ME_Prior_1_0": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_Prior_1_0_CSV.zip",
    "6_Portfolios_ME_Prior_1_0_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_Prior_1_0_Daily_CSV.zip",
    "25_Portfolios_ME_Prior_1_0": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_Prior_1_0_CSV.zip",
    "25_Portfolios_ME_Prior_1_0_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_Prior_1_0_Daily_CSV.zip",
    "10_Portfolios_Prior_1_0": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/10_Portfolios_Prior_1_0_CSV.zip",
    "10_Portfolios_Prior_1_0_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/10_Portfolios_Prior_1_0_Daily_CSV.zip",
    "F-F_LT_Reversal_Factor": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_LT_Reversal_Factor_CSV.zip",
    "F-F_LT_Reversal_Factor_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_LT_Reversal_Factor_daily_CSV.zip",
    "6_Portfolios_ME_Prior_60_13": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_Prior_60_13_CSV.zip",
    "6_Portfolios_ME_Prior_60_13_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/6_Portfolios_ME_Prior_60_13_Daily_CSV.zip",
    "25_Portfolios_ME_Prior_60_13": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_Prior_60_13_CSV.zip",
    "25_Portfolios_ME_Prior_60_13_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_Prior_60_13_Daily_CSV.zip",
    "10_Portfolios_Prior_60_13": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/10_Portfolios_Prior_60_13_CSV.zip",
    "10_Portfolios_Prior_60_13_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/10_Portfolios_Prior_60_13_Daily_CSV.zip",
    "Portfolios_Formed_on_AC": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_AC_CSV.zip",
    "25_Portfolios_ME_AC_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_AC_5x5_CSV.zip",
    "Portfolios_Formed_on_BETA": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_BETA_CSV.zip",
    "25_Portfolios_ME_BETA_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_BETA_5x5_CSV.zip",
    "Portfolios_Formed_on_NI": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_NI_CSV.zip",
    "25_Portfolios_ME_NI_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_NI_5x5_CSV.zip",
    "Portfolios_Formed_on_VAR": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_VAR_CSV.zip",
    "25_Portfolios_ME_VAR_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_VAR_5x5_CSV.zip",
    "Portfolios_Formed_on_RESVAR": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Portfolios_Formed_on_RESVAR_CSV.zip",
    "25_Portfolios_ME_RESVAR_5x5": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/25_Portfolios_ME_RESVAR_5x5_CSV.zip",
    "5_Industry_Portfolios": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/5_Industry_Portfolios_CSV.zip",
    "5_Industry_Portfolios_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/5_Industry_Portfolios_Wout_Div_CSV.zip",
    "5_Industry_Portfolios_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/5_Industry_Portfolios_daily_CSV.zip",
    "10_Industry_Portfolios": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/10_Industry_Portfolios_CSV.zip",
    "10_Industry_Portfolios_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/10_Industry_Portfolios_Wout_Div_CSV.zip",
    "10_Industry_Portfolios_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/10_Industry_Portfolios_daily_CSV.zip",
    "12_Industry_Portfolios": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/12_Industry_Portfolios_CSV.zip",
    "12_Industry_Portfolios_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/12_Industry_Portfolios_Wout_Div_CSV.zip",
    "12_Industry_Portfolios_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/12_Industry_Portfolios_daily_CSV.zip",
    "17_Industry_Portfolios": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/17_Industry_Portfolios_CSV.zip",
    "17_Industry_Portfolios_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/17_Industry_Portfolios_Wout_Div_CSV.zip",
    "17_Industry_Portfolios_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/17_Industry_Portfolios_daily_CSV.zip",
    "30_Industry_Portfolios": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/30_Industry_Portfolios_CSV.zip",
    "30_Industry_Portfolios_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/30_Industry_Portfolios_Wout_Div_CSV.zip",
    "30_Industry_Portfolios_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/30_Industry_Portfolios_daily_CSV.zip",
    "38_Industry_Portfolios": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/38_Industry_Portfolios_CSV.zip",
    "38_Industry_Portfolios_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/38_Industry_Portfolios_Wout_Div_CSV.zip",
    "38_Industry_Portfolios_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/38_Industry_Portfolios_daily_CSV.zip",
    "48_Industry_Portfolios": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/48_Industry_Portfolios_CSV.zip",
    "48_Industry_Portfolios_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/48_Industry_Portfolios_Wout_Div_CSV.zip",
    "48_Industry_Portfolios_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/48_Industry_Portfolios_daily_CSV.zip",
    "49_Industry_Portfolios": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/49_Industry_Portfolios_CSV.zip",
    "49_Industry_Portfolios_Wout_Div": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/49_Industry_Portfolios_Wout_Div_CSV.zip",
    "49_Industry_Portfolios_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/49_Industry_Portfolios_daily_CSV.zip",
    "ME_Breakpoints": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/ME_Breakpoints_CSV.zip",
    "BE-ME_Breakpoints": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/BE-ME_Breakpoints_CSV.zip",
    "OP_Breakpoints": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/OP_Breakpoints_CSV.zip",
    "INV_Breakpoints": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/INV_Breakpoints_CSV.zip",
    "E-P_Breakpoints": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/E-P_Breakpoints_CSV.zip",
    "CF-P_Breakpoints": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/CF-P_Breakpoints_CSV.zip",
    "D-P_Breakpoints": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/D-P_Breakpoints_CSV.zip",
    "Prior_2-12_Breakpoints": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Prior_2-12_Breakpoints_CSV.zip",
    "Developed_3_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_3_Factors_CSV.zip",
    "Developed_3_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_3_Factors_Daily_CSV.zip",
    "Developed_ex_US_3_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_3_Factors_CSV.zip",
    "Developed_ex_US_3_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_3_Factors_Daily_CSV.zip",
    "Europe_3_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_3_Factors_CSV.zip",
    "Europe_3_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_3_Factors_Daily_CSV.zip",
    "Japan_3_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_3_Factors_CSV.zip",
    "Japan_3_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_3_Factors_Daily_CSV.zip",
    "Asia_Pacific_ex_Japan_3_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_3_Factors_CSV.zip",
    "Asia_Pacific_ex_Japan_3_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_3_Factors_Daily_CSV.zip",
    "North_America_3_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_3_Factors_CSV.zip",
    "North_America_3_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_3_Factors_Daily_CSV.zip",
    "Developed_5_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_5_Factors_CSV.zip",
    "Developed_5_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_5_Factors_Daily_CSV.zip",
    "Developed_ex_US_5_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_5_Factors_CSV.zip",
    "Developed_ex_US_5_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_5_Factors_Daily_CSV.zip",
    "Europe_5_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_5_Factors_CSV.zip",
    "Europe_5_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_5_Factors_Daily_CSV.zip",
    "Japan_5_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_5_Factors_CSV.zip",
    "Japan_5_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_5_Factors_Daily_CSV.zip",
    "Asia_Pacific_ex_Japan_5_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_5_Factors_CSV.zip",
    "Asia_Pacific_ex_Japan_5_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_5_Factors_Daily_CSV.zip",
    "North_America_5_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_5_Factors_CSV.zip",
    "North_America_5_Factors_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_5_Factors_Daily_CSV.zip",
    "Developed_Mom_Factor": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_Mom_Factor_CSV.zip",
    "Developed_Mom_Factor_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_Mom_Factor_Daily_CSV.zip",
    "Developed_ex_US_Mom_Factor": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_Mom_Factor_CSV.zip",
    "Developed_ex_US_Mom_Factor_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_Mom_Factor_Daily_CSV.zip",
    "Europe_Mom_Factor": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_Mom_Factor_CSV.zip",
    "Europe_Mom_Factor_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_Mom_Factor_Daily_CSV.zip",
    "Japan_Mom_Factor": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_Mom_Factor_CSV.zip",
    "Japan_Mom_Factor_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_Mom_Factor_Daily_CSV.zip",
    "Asia_Pacific_ex_Japan_MOM_Factor": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_MOM_Factor_CSV.zip",
    "Asia_Pacific_ex_Japan_MOM_Factor_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_MOM_Factor_Daily_CSV.zip",
    "North_America_Mom_Factor": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_Mom_Factor_CSV.zip",
    "North_America_Mom_Factor_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_Mom_Factor_Daily_CSV.zip",
    "Developed_6_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_6_Portfolios_ME_BE-ME_CSV.zip",
    "Developed_6_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_6_Portfolios_ME_BE-ME_daily_CSV.zip",
    "Developed_ex_US_6_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_6_Portfolios_ME_BE-ME_CSV.zip",
    "Developed_ex_US_6_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_6_Portfolios_ME_BE-ME_daily_CSV.zip",
    "Europe_6_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_6_Portfolios_ME_BE-ME_CSV.zip",
    "Europe_6_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_6_Portfolios_ME_BE-ME_daily_CSV.zip",
    "Japan_6_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_6_Portfolios_ME_BE-ME_CSV.zip",
    "Japan_6_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_6_Portfolios_ME_BE-ME_daily_CSV.zip",
    "Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME_CSV.zip",
    "Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME_daily_CSV.zip",
    "North_America_6_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_6_Portfolios_ME_BE-ME_CSV.zip",
    "North_America_6_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_6_Portfolios_ME_BE-ME_daily_CSV.zip",
    "Developed_25_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_25_Portfolios_ME_BE-ME_CSV.zip",
    "Developed_25_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_25_Portfolios_ME_BE-ME_daily_CSV.zip",
    "Developed_ex_US_25_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_25_Portfolios_ME_BE-ME_CSV.zip",
    "Developed_ex_US_25_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_25_Portfolios_ME_BE-ME_daily_CSV.zip",
    "Europe_25_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_25_Portfolios_ME_BE-ME_CSV.zip",
    "Europe_25_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_25_Portfolios_ME_BE-ME_daily_CSV.zip",
    "Japan_25_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_25_Portfolios_ME_BE-ME_CSV.zip",
    "Japan_25_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_25_Portfolios_ME_BE-ME_daily_CSV.zip",
    "Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME_CSV.zip",
    "Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME_daily_CSV.zip",
    "North_America_25_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_25_Portfolios_ME_BE-ME_CSV.zip",
    "North_America_25_Portfolios_ME_BE-ME_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_25_Portfolios_ME_BE-ME_daily_CSV.zip",
    "Developed_6_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_6_Portfolios_ME_OP_CSV.zip",
    "Developed_6_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_6_Portfolios_ME_OP_Daily_CSV.zip",
    "Developed_ex_US_6_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_6_Portfolios_ME_OP_CSV.zip",
    "Developed_ex_US_6_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_6_Portfolios_ME_OP_Daily_CSV.zip",
    "Europe_6_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_6_Portfolios_ME_OP_CSV.zip",
    "Europe_6_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_6_Portfolios_ME_OP_Daily_CSV.zip",
    "Japan_6_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_6_Portfolios_ME_OP_CSV.zip",
    "Japan_6_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_6_Portfolios_ME_OP_Daily_CSV.zip",
    "Asia_Pacific_ex_Japan_6_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_6_Portfolios_ME_OP_CSV.zip",
    "Asia_Pacific_ex_Japan_6_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_6_Portfolios_ME_OP_Daily_CSV.zip",
    "North_America_6_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_6_Portfolios_ME_OP_CSV.zip",
    "North_America_6_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_6_Portfolios_ME_OP_Daily_CSV.zip",
    "Developed_25_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_25_Portfolios_ME_OP_CSV.zip",
    "Developed_25_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_25_Portfolios_ME_OP_Daily_CSV.zip",
    "Developed_ex_US_25_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_25_Portfolios_ME_OP_CSV.zip",
    "Developed_ex_US_25_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_25_Portfolios_ME_OP_Daily_CSV.zip",
    "Europe_25_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_25_Portfolios_ME_OP_CSV.zip",
    "Europe_25_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_25_Portfolios_ME_OP_Daily_CSV.zip",
    "Japan_25_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_25_Portfolios_ME_OP_CSV.zip",
    "Japan_25_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_25_Portfolios_ME_OP_Daily_CSV.zip",
    "Asia_Pacific_ex_Japan_25_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_25_Portfolios_ME_OP_CSV.zip",
    "Asia_Pacific_ex_Japan_25_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_25_Portfolios_ME_OP_Daily_CSV.zip",
    "North_America_25_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_25_Portfolios_ME_OP_CSV.zip",
    "North_America_25_Portfolios_ME_OP_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_25_Portfolios_ME_OP_Daily_CSV.zip",
    "Developed_6_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_6_Portfolios_ME_INV_CSV.zip",
    "Developed_6_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_6_Portfolios_ME_INV_Daily_CSV.zip",
    "Developed_ex_US_6_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_6_Portfolios_ME_INV_CSV.zip",
    "Developed_ex_US_6_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_6_Portfolios_ME_INV_Daily_CSV.zip",
    "Europe_6_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_6_Portfolios_ME_INV_CSV.zip",
    "Europe_6_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_6_Portfolios_ME_INV_Daily_CSV.zip",
    "Japan_6_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_6_Portfolios_ME_INV_CSV.zip",
    "Japan_6_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_6_Portfolios_ME_INV_Daily_CSV.zip",
    "Asia_Pacific_ex_Japan_6_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_6_Portfolios_ME_INV_CSV.zip",
    "Asia_Pacific_ex_Japan_6_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_6_Portfolios_ME_INV_Daily_CSV.zip",
    "North_America_6_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_6_Portfolios_ME_INV_CSV.zip",
    "North_America_6_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_6_Portfolios_ME_INV_Daily_CSV.zip",
    "Developed_25_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_25_Portfolios_ME_INV_CSV.zip",
    "Developed_25_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_25_Portfolios_ME_INV_Daily_CSV.zip",
    "Developed_ex_US_25_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_25_Portfolios_ME_INV_CSV.zip",
    "Developed_ex_US_25_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_25_Portfolios_ME_INV_Daily_CSV.zip",
    "Europe_25_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_25_Portfolios_ME_INV_CSV.zip",
    "Europe_25_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_25_Portfolios_ME_INV_Daily_CSV.zip",
    "Japan_25_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_25_Portfolios_ME_INV_CSV.zip",
    "Japan_25_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_25_Portfolios_ME_INV_Daily_CSV.zip",
    "Asia_Pacific_ex_Japan_25_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_25_Portfolios_ME_INV_CSV.zip",
    "Asia_Pacific_ex_Japan_25_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_25_Portfolios_ME_INV_Daily_CSV.zip",
    "North_America_25_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_25_Portfolios_ME_INV_CSV.zip",
    "North_America_25_Portfolios_ME_INV_Daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_25_Portfolios_ME_INV_Daily_CSV.zip",
    "Developed_6_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_6_Portfolios_ME_Prior_12_2_CSV.zip",
    "Developed_6_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_6_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "Developed_ex_US_6_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_6_Portfolios_ME_Prior_12_2_CSV.zip",
    "Developed_ex_US_6_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_6_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "Europe_6_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_6_Portfolios_ME_Prior_12_2_CSV.zip",
    "Europe_6_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_6_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "Japan_6_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_6_Portfolios_ME_Prior_12_2_CSV.zip",
    "Japan_6_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_6_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_12_2_CSV.zip",
    "Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "North_America_6_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_6_Portfolios_ME_Prior_12_2_CSV.zip",
    "North_America_6_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_6_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "Developed_25_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_25_Portfolios_ME_Prior_12_2_CSV.zip",
    "Developed_25_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_25_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "Developed_ex_US_25_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_25_Portfolios_ME_Prior_12_2_CSV.zip",
    "Developed_ex_US_25_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_25_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "Europe_25_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_25_Portfolios_ME_Prior_12_2_CSV.zip",
    "Europe_25_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_25_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "Japan_25_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_25_Portfolios_ME_Prior_12_2_CSV.zip",
    "Japan_25_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_25_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_12_2_CSV.zip",
    "Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "North_America_25_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_25_Portfolios_ME_Prior_12_2_CSV.zip",
    "North_America_25_Portfolios_ME_Prior_250_20_daily": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_25_Portfolios_ME_Prior_250_20_daily_CSV.zip",
    "Developed_32_Portfolios_ME_BE-ME_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_32_Portfolios_ME_BE-ME_OP_2x4x4_CSV.zip",
    "Developed_ex_US_32_Portfolios_ME_BE-ME_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_32_Portfolios_ME_BE-ME_OP_2x4x4_CSV.zip",
    "Europe_32_Portfolios_ME_BE-ME_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_32_Portfolios_ME_BE-ME_OP_2x4x4_CSV.zip",
    "Japan_32_Portfolios_ME_BE-ME_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_32_Portfolios_ME_BE-ME_OP_2x4x4_CSV.zip",
    "Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_OP_2x4x4_CSV.zip",
    "North_America_32_Portfolios_ME_BE-ME_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_32_Portfolios_ME_BE-ME_OP_2x4x4_CSV.zip",
    "Developed_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4_CSV.zip",
    "Developed_ex_US_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4_CSV.zip",
    "Europe_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4_CSV.zip",
    "Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4_CSV.zip",
    "Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4_CSV.zip",
    "North_America_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4_CSV.zip",
    "Developed_32_Portfolios_ME_INV(TA)_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_32_Portfolios_ME_INV(TA)_OP_2x4x4_CSV.zip",
    "Developed_ex_US_32_Portfolios_ME_INV(TA)_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Developed_ex_US_32_Portfolios_ME_INV(TA)_OP_2x4x4_CSV.zip",
    "Europe_32_Portfolios_ME_INV(TA)_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Europe_32_Portfolios_ME_INV(TA)_OP_2x4x4_CSV.zip",
    "Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4_CSV.zip",
    "Asia_Pacific_ex_Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Asia_Pacific_ex_Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4_CSV.zip",
    "North_America_32_Portfolios_ME_INV(TA)_OP_2x4x4": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/North_America_32_Portfolios_ME_INV(TA)_OP_2x4x4_CSV.zip",
    "Emerging_5_Factors": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Emerging_5_Factors_CSV.zip",
    "Emerging_MOM_Factor": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Emerging_MOM_Factor_CSV.zip",
    "Emerging_Markets_6_Portfolios_ME_BE-ME": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Emerging_Markets_6_Portfolios_ME_BE-ME_CSV.zip",
    "Emerging_Markets_6_Portfolios_ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Emerging_Markets_6_Portfolios_ME_OP_CSV.zip",
    "Emerging_Markets_6_Portfolios_ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Emerging_Markets_6_Portfolios_ME_INV_CSV.zip",
    "Emerging_Markets_6_Portfolios_ME_Prior_12_2": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Emerging_Markets_6_Portfolios_ME_Prior_12_2_CSV.zip",
    "Emerging_Markets_4_Portfolios_BE-ME_OP": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Emerging_Markets_4_Portfolios_BE-ME_OP_CSV.zip",
    "Emerging_Markets_4_Portfolios_OP_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Emerging_Markets_4_Portfolios_OP_INV_CSV.zip",
    "Emerging_Markets_4_Portfolios_BE-ME_INV": "http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/Emerging_Markets_4_Portfolios_BE-ME_INV_CSV.zip",
}


COUNTRY_PORTFOLIOS_URLS = {
    "dividends": "https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_International_Countries.zip",
    "ex": "https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_International_Countries_Wout_Div.zip",
}

COUNTRY_PORTFOLIO_FILES = {
    "Austria": "Austria.Dat",
    "Australia": "Australia.Dat",
    "Belgium": "Belgium.Dat",
    "Canada": "Canada.Dat",
    "Denmark": "Denmark.Dat",
    "Finland": "Finland.Dat",
    "France": "France.Dat",
    "Germany": "Germany.Dat",
    "Hong Kong": "HongKong.Dat",
    "Ireland": "Ireland.Dat",
    "Italy": "Italy.Dat",
    "Japan": "Japan.Dat",
    "Malaysia": "Malaysia.Dat",
    "Netherlands": "Nethrlnd.Dat",
    "New Zealand": "NewZland.Dat",
    "Norway": "Norway.Dat",
    "Singapore": "Singapor.Dat",
    "Spain": "Spain.Dat",
    "Sweden": "Sweden.Dat",
    "Switzerland": "Swtzrlnd.Dat",
    "United Kingdom": "UK.Dat",
}

INTERNATIONAL_INDEX_PORTFOLIOS_URLS = {
    "dividends": "https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_International_Indices.zip",
    "ex": "https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_International_Indices_Wout_Div.zip",
}

INTERNATIONAL_INDEX_PORTFOLIO_FILES = {
    "UK": "Ind_UK.Dat",
    "Scandinavia": "Ind_Scandinavia.Dat",
    "Europe": "Ind_Eur_With_UK.Dat",
    "Europe ex-UK": "Ind_Eur_WOut_UK.Dat",
    "Asia Pacific": "Ind_Asia_Pac.Dat",
    "All": "Ind_all.Dat",
}

REGIONS = [
    "North_America",
    "Europe",
    "Japan",
    "Asia_Pacific_ex_Japan",
    "Developed",
    "Developed_ex_US",
    "Emerging",
]
